development:
  adapter: postgresql
  encoding: unicode
  host: ec2-54-217-239-20.eu-west-1.compute.amazonaws.com
  database: d3but2lp0cosgb
  pool: 5
  username: plbtohhtwhmule
  password: glk7i7y2_SobOzMo7g2QEGYhIp